### ISSUE TITLE
User Story: Configure Satellite to handle offline installing for discovery

### ISSUE THREAD

**Issue by myersCody** [redhat-discovery/discovery#220]
- [x] **Task One:** Setup up a satellite on a vCenter VM
- [x] **Task Two:** (Satellite configuration) Document the steps to configure and mirror the discovery container and rpms
- [x] **Task Three:** (Client/Podman changes) Document the steps required to authenticate and use above satellite (these are the steps we must automate)
- [x] **Task Four:** Propose a way to enhance the installer to work with satellite
- [ ] **Task Five:** Implement proposal after team signoff

**Comment by myersCody** [comment]
Our current satellite configuration had a dependencies error, probably caused by the mix of offline/online installs that I did between Friday & now. I have spent the last hour debugging it with Christian and we believe we have the dependencies error sorted out so that we can upgrade satellite versions whenever we want to.

We are still missing a manifest that has the following subscription attached:
```
Subscription Name:   Red Hat Satellite Infrastructure Subscription
Provides:            Red Hat Satellite
                     Red Hat Software Collections (for RHEL Server)
                     Red Hat CodeReady Linux Builder for x86_64
                     Red Hat Satellite Capsule
                     Red Hat Ansible Engine
                     Red Hat Satellite with Embedded Oracle
                     Red Hat Satellite 5 Managed DB
                     Red Hat Enterprise Linux Load Balancer (for RHEL Server)
                     Red Hat Beta
                     Red Hat Software Collections Beta (for RHEL Server)
                     Red Hat Enterprise Linux Server
                     Red Hat Enterprise Linux for x86_64
                     Red Hat Satellite Proxy
                     Red Hat Enterprise Linux High Availability for x86_64
                     Red Hat Discovery
SKU:                 MCT3718
Contract:            
Pool ID:             8a85f99b6d889887016ddd3ec2a3610d
Provides Management: Yes
Available:           1
Suggested:           1
Service Level:       Premium
Service Type:        L1-L3
Subscription Type:   Standard
Starts:              10/18/2019
Ends:                10/17/2024
System Type:         Physical
```

I did find some manifests that we can use; however, all of the ones that worked were before Discovery was finished. Therefore, I have reached out to Rich who agreed to create a manifest for us that we can upload into Satellite in the morning.

**Comment by myersCody** [comment]
### Task Number Three
- (Client/Podman changes) Document the steps required to authenticate and use above satellite (these are the steps we must automate)

---

For this step, configuring a new system to use an already established and configured satellite is actually really easy. 

#### Step One: Install the Consumer RPM

First, we have to install the katello consumer rpm which is created and has details regarding satellite built into the package. 

```
yum install -y http://$(satellite_host)/pub/katello-ca-consumer-latest.noarch.rpm
```
This rpm is actually located where ever the satellite host has been setup at; for example, the `$(satellite_host)` variable could be an ip address or a hostname. 

#### Step Two: System registration with activation key
After the consumer package has been installed, we then register it with the satellite host. We do this by creating an activation key, and that key then becomes the authority of which repos the consumer has access to. 

	subscription-manager register --org="$(satellite_org)" --activationkey="$(satellite_key)"

- The `$(satellite_key)` parameter is whatever the user decides to name the activation key.
- The `$(satellite_org)` parameter is whatever organization the key is associated with upon creation. 

The user can also find the exact register command in the satellite UI by going to: 
`Content->Activation Keys->$(satellite_key)`. 

---

**Additional Notes:**

These steps may be optional depending on how much the customer uses satellite. If they already have a consumer created and connected through an activation key, the user may just want to add the repos needed to run discovery to their activation key.

**Comment by myersCody** [comment]
### Task Number Four:
- Propose a way to enhance the installer to work with satellite
---

Design for enhance located here: https://github.com/quipucords/qpc-tools/issues/73
